name: mobile_app_flutter
description: Приложение для изучения языков на Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # HTTP
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^13.0.0
  
  # Speech Recognition
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0
  
  # Audio
  record: ^5.0.4
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf









